### ISSUE TITLE
Настройка комплекса

### ISSUE THREAD

**Issue by vszaharchenko** [autocomp/fluffy-dollop#7]
Если указать путь к папке с исходными данными в application_settings.xml  без закрывающего "/", то путь определиться неверно и прога работать не будет, например:
**Region Biz can't open config file: ~/projects/strup/contour_ngconfig.json**

**Comment by AlgisOthal** [comment]
Сам конфиг по честному берется по пути до ФАЙЛА, а не КАТАЛОГА, как было.
Пути к файлам при чтении тоже поправил.
