### ISSUE TITLE
Настройка работы с базой данных

### ISSUE THREAD

**Issue by vszaharchenko** [autocomp/fluffy-dollop#8]
Файл настройки работы с базой данных располагается в "левом" каталоге, надо его перетащить туда, где лежат все конфиги, да и конфиг можно использовать какой-нибудь из существующих, например application_settings.xml. Базу и всю остальную требуху пока предлагаю разместить в каталоге bin/base, чтобы было удобно деплоиться. Позже, когда данные будут распухать, вопрос инсталляции пересмотрим

**Comment by AlgisOthal** [comment]
конфиг для настройки regionbiz свой из соображений повышенной динамичности настройки иерархии конфигурации по типам трансляции и т.п., по этой же причине json). И никак иначе =)

Сами конфиги перенесены в каталог с конфигурациями, в application_settings.xml путь до конфига regionbiz, файлового хранилища.

База может располагаться, впринципе, где угодно. Но я поддерживаю ./bin/base. Хотя это уже не актуально - переход на Postgress уже осуществлен.
